routes/article.py
from flask import Blueprint, render_template

article_bp = Blueprint('article', __name__)


@article_bp.route('/articles')
def articles():
    return render_template("articles.html",title="Articles",
                           message="At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum")

routes/main.py
from flask import Blueprint, render_template

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
@main_bp.route('/home')
@main_bp.route('/index')
def index():
    return render_template("index.html")

@main_bp.route('/about')
def about():
    return render_template("about.html",
                           title="About Us",
                           message="At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum")

@main_bp.route('/history')
def history():
    return render_template("history.html",
                           title="History",
                           message="At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum")

routes/myths.py
from flask import Blueprint, render_template

myths_bp = Blueprint('myths', __name__)


@myths_bp.route('/myths')
def myths():
    return render_template("myths.html")

templates/partials/footer.html
<footer class="p-50">
    <div class="mt-50 flex-column row-gap-20">
        <div class="flex-row row-gap-30 flex-wrap">
            <div class="flex-column row-gap-20">
                <a href="{{url_for('main.index')}}">
                <img src="{{url_for('static',filename='Images/white_logo.png')}}" alt="1Palestine Logo" width="150px">
                </a>
                <div class="flex-row column-gap-30">
                    <span><a href="{{url_for('main.history')}}">History</a></span>
                    <span><a href="{{url_for('article.articles')}}">Articles</a></span>
                    <span><a href="{{url_for('myths.myths')}}">Zionist Myths</a></span>
                    <span><a >Resources</a></span>
                    <span><a href="{{url_for('main.about')}}">About Us</a></span>
                    <span><a>Take Action</a></span>
                </div>
            </div>
            <div>
                <h3 class="font-20 mb-10">Join newsletter</h3>
                <input class="newsletter p-5 pl-30 font-18" type="email" placeholder="Your email">
            </div>
        </div>
        <hr>
        <div>
            <p>© 2025 1Palestine</p>
        </div>
    </div>
</footer>
<style>
    footer a,footer a:hover,footer a:active{
       color:white;
    }
  footer div div div{
    flex-grow:3;
  }
  .newsletter{
    border-radius: 5px;
  }
</style>

templates/partials/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Discover the rich tapestry of Palestinian history through an interactive educational journey. Explore cultural heritage, historical timelines, and compelling stories.">
    
    <!-- Open Graph Tags -->
    <meta property="og:title" content="Palestinian History | Interactive Educational Journey">
    <meta property="og:description" content="Explore Palestinian heritage through interactive timelines, galleries, and stories.">
    <meta property="og:image" content="https://www.1palestine.org/cover">
    <!-- Favicon -->
    <link rel="icon" type="image/ico" href="/static/icons/favicon.ico">
    <link rel="stylesheet" href="/static/css/styles.css">
     <link rel="stylesheet" href="/static/css/responsive.css">
    <title>1Palestine</title>
</head>
<body dir="ltr">

   {% include 'partials/navbar.html' %}
    {% block content %}{% endblock %}
    {% include 'partials/footer.html' %}

</script>

</body>
</html>

templates/partials/navbar.html
<nav class="p-30 pl-50  flex-column row-gap-20 w-100">
  <div class="column-gap-20 flex-row ai-center jc-spaceb">
    <a href="{{url_for('main.index')}}">
      <img src="{{url_for('static',filename='Images/black_logo.png')}}" alt="1Palestine Logo" width="150px">
    </a>
  
    <div class="nav-toggle flex-row column-gap-30 weight-700">
      <span><a href="{{url_for('main.history')}}">History</a></span>
      <span><a href="{{url_for('article.articles')}}">Articles</a></span>
      <span><a href="{{url_for('myths.myths')}}">Zionist Myths</a></span>
      <span><a>Resources</a></span>
      <span><a  href="{{url_for('main.about')}}">About Us</a></span>
    </div>
    <div>
      <button class="weight-700">Take Action</button>
    </div> 
    <div class="toggle">

    </div>
  </div>
  <div class="toggle_links">
    <div class="flex-column row-gap-10 weight-700 jc-end">
      <span><a href="{{url_for('main.history')}}">History</a></span>
      <span><a href="{{url_for('article.articles')}}">Articles</a></span>
      <span><a href="{{url_for('myths.myths')}}">Zionist Myths</a></span>
      <span><a>Resources</a></span>
      <span><a href="{{url_for('main.about')}}">About Us</a></span>
    </div>
  </div>
  </nav>
<style>
   nav a,nav a:hover,nav a:active{
       color:black;
    }
  nav button{
    border:none;
    border-radius:5px;
    padding:8px;
    color:white;
    background:black;
  }
  .toggle{
    border-top:2px solid black;
    border-bottom:2px solid black;
    width:30px;
    height:20px;
    padding-top:9px;
    padding-bottom:9px;
  }
  .toggle::before{
    content:".";
    display:inline-block;
    width:100%;
    height:2px;
    background: black;
  }
  .toggle_links{
    display:none;
    margin-top:20px;
    width:100%;
  }
  @media only screen and (max-width: 920px) {
   .toggle{
    display:block !important;
    justify-self:end !important;
  }
    .nav-toggle{
      display:none !important;
    }
    .v-line{
      display:none;
    }
    nav> div >div:nth-child(3){
    display:none;
  }
}
</style>
<script type="text/javascript">
let visible = false;
document.querySelector(".toggle").onclick=()=>{
  document.querySelector(".toggle_links")
  .style.display = visible ? "none":"flex"
  visible=!visible;
}

window.onresize=()=>{
  
  document.querySelector(".toggle_links").style.display="none"
  visible = false;
}

</script>